### ISSUE TITLE
Anticheat On or Anticheat Off

### ISSUE THREAD

**Issue by MateoNikolic** [skeltalgit/LunarClientAPI#2]
Hey, thank you for contributing to community with this amazing plugin and API. I was wondering if it's possible to add a system that will detect if player has anticheat enabled or anticheat disabled while playing on Lunar Client. In that way we could easily make cheater free UHC Games and I think it'd contribute to any server that has to deal with cheaters all the time.

**Comment by skeltalgit** [comment]
Hi, unfortunately Lunar Client uses AAL to verify that players have the anti-cheat enabled which means at this point we have no way of having a 100% accurate method to check on our end.

On a related note - Lunar's own API is also not 100% accurate at detecting whether a player has the anticheat enabled (See https://gyazo.com/cd5e32f9c3d83e98821794c8a70e1ccb - this server is using an official Lunar API)
