### ISSUE TITLE
Getting kicked for not having Lunar client, while on lunar client.

### ISSUE THREAD

**Issue by CyberSecGuy** [skeltalgit/LunarClientAPI#3]
Not sure if there was an update breaking this plugin, but I keep getting kicked for not having Lunar client, while I'm on Lunar client.

Thanks!

**Comment by SolarOfficial** [comment]
Its probably because you must have the anticheat on to detect lunar client.

**Comment by TewPingz** [comment]
does that solve your issue? @CyberSecGuy
