### ISSUE TITLE
plz jar

### ISSUE THREAD

**Issue by KaguraMatsuri** [skeltalgit/LunarClientAPI#6]
plz .jar

**Comment by ghost** [comment]
There is a .jar in the releases section.

**Comment by KaguraMatsuri** [comment]
Sorry, I can't find it.

**Comment by ghost** [comment]
https://github.com/TewPingz/LunarClientAPI/releases/tag/Plugin-304042b there you go

**Comment by KaguraMatsuri** [comment]
thx
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Refreezinq"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月18日(星期四) 凌晨5:26
收件人:&nbsp;"TewPingz/LunarClientAPI"<LunarClientAPI@noreply.github.com&gt;;
抄送:&nbsp;"神樂 祭"<1283962190@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TewPingz/LunarClientAPI] plz jar (#6)





 
https://github.com/TewPingz/LunarClientAPI/releases/tag/Plugin-304042b there you go
