### ISSUE TITLE
Staff Module Enable

### ISSUE THREAD

**Issue by FreshNike** [skeltalgit/LunarClientAPI#7]
Related To Issue #5,

 I'm not very good in java but, where would I put LunarClientPlugin.getApi().toggleStaffModule(player, StaffModule.XRAY, true); 
in the ide. 
![image](https://user-images.githubusercontent.com/65096540/86427797-3016e580-bcb9-11ea-98c8-5cf7db528f43.png)

**Comment by TewPingz** [comment]
thats up to you, you could make a bukkit listener, listen for the authenticate event and when a player gets authenticated you can check for a permission and then enable the staff module if the user authenticated has the permission.
