### ISSUE TITLE
Tried to enable staff mods, doesnt work.

### ISSUE THREAD

**Issue by kodalee** [skeltalgit/LunarClientAPI#8]
LunarClientPlugin.getApi().toggleStaffModule(player, "XRAY", true);

Need help thanks <3

**Comment by TewPingz** [comment]
can you show me the code you are trying to run to enable it?

**Comment by kodalee** [comment]
An OnJoin event, I fixed the code by replacing "XRAY" with StaffModule.valueOf("XRAY")

The code works but not on the 1.8 version... (outdated packets being sent?)

```java
if (event.getPlayer().hasPermission("prime.staff")) {
     Player player = event.getPlayer();
     if (LunarClientPlugin.getApi().isAuthenticated(player)) {
           LunarClientPlugin.getApi().sendNotification(player, "You now have access to staff mods in your Lunar Client, Access with RSHIFT menu.", Notification.valueOf("INFO"), 5);
           LunarClientPlugin.getApi().toggleStaffModule(player, StaffModule.valueOf("NAME_TAGS"), true);
           LunarClientPlugin.getApi().toggleStaffModule(player, StaffModule.valueOf("BUNNY_HOP"), true);
           LunarClientPlugin.getApi().toggleStaffModule(player, StaffModule.valueOf("XRAY"), true);
     }
}
```

**Comment by TewPingz** [comment]
what you did was fine but for efficiency use this instead:

```java        
if (event.getPlayer().hasPermission("prime.staff")) {
            Player player = event.getPlayer();
            if (LunarClientPlugin.getApi().isAuthenticated(player)) {
                LunarClientPlugin.getApi().sendNotification(player, "You now have access to staff mods in your Lunar Client, Access with RSHIFT menu.", Notification.INFO, 5);
                LunarClientPlugin.getApi().toggleStaffModule(player, StaffModule.NAME_TAGS, true);
                LunarClientPlugin.getApi().toggleStaffModule(player, StaffModule.BUNNY_HOP, true);
                LunarClientPlugin.getApi().toggleStaffModule(player, StaffModule.XRAY, true);
            }
        }
```

and you can also use the AuthenticateEvent so it will only attempt to toggle the staffModules for the users on lunar

**Comment by kodalee** [comment]
ok, i tried this and it doesnt work on 1.8, is it what i pointed out?

**Comment by TewPingz** [comment]
mate you were using strings and not the actual enum value, it has nothing to do with minecraft versioning, you just used it wrong.

and if the modules are still not enabling, again i said use the authenticate event since the player hasnt registered the actual lunar-client channel to receive the lunar client mods

or you could also have a delay of like a second and then attempting to send the packet in the join event.

**Comment by TewPingz** [comment]
if you want the code mate here:

```java
    @EventHandler
    public void onAuthenticate(AuthenticateEvent event) {
        if (event.getPlayer().hasPermission("prime.staff")) {
            Player player = event.getPlayer();
            if (LunarClientPlugin.getApi().isAuthenticated(player)) {
                LunarClientPlugin.getApi().sendNotification(player, "You now have access to staff mods in your Lunar Client, Access with RSHIFT menu.", Notification.INFO, 5);
                LunarClientPlugin.getApi().toggleStaffModule(player, StaffModule.NAME_TAGS, true);
                LunarClientPlugin.getApi().toggleStaffModule(player, StaffModule.BUNNY_HOP, true);
                LunarClientPlugin.getApi().toggleStaffModule(player, StaffModule.XRAY, true);
            }
        }
    }
```

**Comment by kodalee** [comment]
https://www.youtube.com/watch?v=5ZCtoLpQn0Y

I'm using your method and it still doesn't work unfortunately.
As seen in the video, there is a 1 second delay giving enough time for the API to authenticate the client, also it only does this if LunarClientPlugin.getApi().isAuthenticated(player) is a thing.

Any other ideas?

**Comment by kodalee** [comment]
@TewPingz 
bump because idk if you get notifs on a closed issue

**Comment by TewPingz** [comment]
ATM lunar client 1.8 doesn’t have notifications and the staff modules are seen when you enter the mods menu on a bar at the top but non of them work because I believe that haven’t finished making them, that I have no control over

The delay is there because lunar client takes around a second to register it’s Lunar-Client channel and give us the ability to send packets and get responses but there is no way to remove that delay, that is also something I don’t have control over

**Comment by PenguThePenguin** [comment]
I cant enable the staff mods. can someone send me a download to a working plugin? - thanks
